# Generated by Django 4.1.4 on 2025-01-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embalagem',
            name='capacidade_maxima_bolas',
            field=models.PositiveIntegerField(),
        ),
    ]
